spring.application.name=logitrack

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/logitrack
spring.datasource.username=mattias
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway Settings
spring.flyway.enabled=true